# ========== WINDOW SIZES ==========

MAIN_WINDOW_WIDTH = 1000
MAIN_WINDOW_HEIGHT = 600

HELP_WINDOW_WIDTH = 800
HELP_WINDOW_HEIGHT = 600

SET_WINDOW_WIDTH = 900
SET_WINDOW_HEIGHT = 600

SPLASH_WIDTH = 735
SPLASH_HEIGHT = 600

# ========== SOUNDS ==========

SPLASH_MUSIC = "intro_music.mp3"
MAIN_MUSIC = "main_music.mp3"

# ========== BACKGROUND & IMAGES ==========

BACKGROUND_GIF_WIDTH = 1000
BACKGROUND_GIF_HEIGHT = 600

BACKGROUND_IM_WIDTH = 900
BACKGROUND_IM_HEIGHT = 600

SPLASH_BG_IMAGE = "loading_background.jpg"
MAIN_BG_GIFF = "main_background.gif"
SECONDARY_BG_IMAGE = "secondary_background.jpg"


# ========== LAYOUT COORDINATES (MAIN WINDOW) ==========

SAVE_BUTTON_X = 720
SAVE_BUTTON_Y = 20

HELP_BUTTON_X = 720
HELP_BUTTON_Y = 60

SETS_BUTTON_X = 720
SETS_BUTTON_Y = 100

RESULT_FRAME_X = 50
RESULT_FRAME_Y = 360

EXPR_LABEL_X = 50
EXPR_LABEL_Y_1 = 20
EXPR_LABEL_Y_2 = 60
SELECTION_LABEL_Y = 100
VARIABLE_LABEL_Y = 140

EXPR_ENTRY_X = 300
EXPR_ENTRY_Y_1 = 20
EXPR_ENTRY_Y_2 = 60
RADIO_BUTTON_X_1 = 300
RADIO_BUTTON_X_2 = 450
RADIO_BUTTON_Y = 100
VARIABLE_ENTRY_Y = 140

BUTTON_START_X = 150    
BUTTON_START_Y = 200
BUTTON_SPACING_X = 225  
BUTTON_SPACING_Y = 50
BUTTONS_PER_ROW = 3

RESULT_LABEL_X = 575
RESULT_LABEL_Y = 20
RESULT_LABEL_WRAP = 300
RESULT_LABEL_BORDER_WIDTH = 2


# ========== LAYOUT COORDINATES (SETS WINDOW) ==========

SET1_LABEL_X = 20
SET1_LABEL_Y = 20

SET1_ENTRY_X = 20
SET1_ENTRY_Y = 55
SET_ENTRY_WIDTH = 35  

SET2_LABEL_X = 20
SET2_LABEL_Y = 90

SET2_ENTRY_X = 20
SET2_ENTRY_Y = 125

BUTTON_WIDTH_LARGE = 35  
BUTTON_X_FOR_SETS = 60  

BTN_UNION_Y = 170
BTN_INTERSECT_Y = 212
BTN_DIFF_Y = 255
BTN_SYMDIFF_Y = 298
BTN_VENN_Y = 341
BTN_DISJOINT_Y = 384
BTN_CARTPROD_Y = 427
BTN_CARDINALITY_Y = 470
BTN_POWER_Y = 513
BTN_RELATIONS_Y = 556


# ========== BUTTON & WIDGET SIZES/STYLES ==========

BUTTON_WIDTH_1 = 25
BUTTON_WIDTH_2 = 15
BUTTON_FONT = ("Comic Sans MS", 10, "bold")
BUTTON_BG_COLOR = "#f0f0f0"

ENTRY_WIDTH_1 = 40
ENTRY_WIDTH_2 = 20
ENTRY_FONT = ("Comic Sans MS", 12, "bold")
ENTRY_BG_COLOR = "#ffffff"

LABEL_FONT = ("Comic Sans MS", 12, "bold")
LABEL_BG_COLOR = "#ffffff"

RADIO_BUTTON_FONT = ("Comic Sans MS", 12, "bold")
RADIO_BUTTON_BG_COLOR = "#ffffff"

RESULT_DISPLAY_PADX = 10
RESULT_DISPLAY_PADY = 10


# ========== SPLASH (ANIMATION) CONSTANTS ==========

FADE_DURATION = 60
FADE_INTERVAL = 50
SPLASH_TIMEOUT = 7500
TEXT_X_OFFSET = 20
TEXT_Y_OFFSET = 20
UPDATE_BACKGROUND_INTERVAL = 100


# ========== FONTS & PATHS ==========

MYSTERIOUS_FONT_PATH = "C:/Windows/Fonts/Chiller.ttf"
FALLBACK_FONT_PATH = "C:/Windows/Fonts/Arial.ttf"
DEFAULT_FONT_SIZE = 30


# ========== STRINGS / APP TITLES ==========

APP_TITLE = "Logic crusher"
SECONDARY_TITTLE = "Set operations"
HELP_WINDOW_TITLE = "Help window"

RESULT_PLACEHOLDER = "The result will be displayed here."
SAVE_TO_FILE_BUTTON_TEXT = "Save to file"
SETS_BUTTON_TEXT = "Sets"
HELP_BUTTON_TEXT = "Help"

LABEL_EXPR_1_TEXT = "Enter boolean expression 1:"
LABEL_EXPR_2_TEXT = "Enter boolean expression 2:"
LABEL_SELECT_ACTIVE = "Choose an active expression:"
LABEL_DECOMPOSE_VAR = "Variable to decompose:"

SPLASH_QUOTE = (
    "In the silent corridors of reason,\n"
    "logic is the hidden key that unlocks\n"
    "the chaos of our minds."
)
